Repository LionTeam-17/CaloCheck, pull requests merged in 2023-07, with the labels that each got.

#69 fix: foodInfo, nutrient 테스트 코드 에러 수정
  src/main/java/calocheck/boundedContext/foodInfo/entity/FoodInfo.java
  src/test/java/calocheck/boundedContext/cartFoodInfo/controller/CartFoodInfoControllerTests.java
  src/test/java/calocheck/boundedContext/foodInfo/controller/FoodInfoControllerTests.java
  src/test/java/calocheck/boundedContext/foodInfo/service/FoodInfoServiceTests.java
  src/test/java/calocheck/boundedContext/nutrientInfo/service/NutrientInfoServiceTests.java
Labels: bug

#73 Enhancement/66
  src/main/java/calocheck/boundedContext/cartFoodInfo/controller/CartFoodInfoController.java
  src/main/java/calocheck/boundedContext/cartFoodInfo/entity/CartFoodInfo.java
  src/main/java/calocheck/boundedContext/cartFoodInfo/service/CartFoodInfoService.java
  src/main/java/calocheck/boundedContext/dailyFoodInfo/entity/DailyFoodInfo.java
  src/main/java/calocheck/boundedContext/dailyFoodInfo/repository/DailyFoodInfoRepository.java
  src/main/java/calocheck/boundedContext/dailyFoodInfo/service/DailyFoodInfoService.java
  src/main/java/calocheck/boundedContext/dailyMenu/entity/DailyMenu.java
  src/main/java/calocheck/boundedContext/dailyMenu/repository/DailyMenuRepository.java
  src/main/java/calocheck/boundedContext/dailyMenu/service/DailyMenuService.java
  src/main/java/calocheck/boundedContext/mealHistory/entity/MealHistory.java
  src/main/java/calocheck/boundedContext/mealHistory/repository/MealHistoryRepository.java
  src/main/java/calocheck/boundedContext/mealHistory/service/MealHistoryService.java
  src/main/java/calocheck/boundedContext/member/entity/Member.java
  src/main/java/calocheck/boundedContext/nutrient/entity/Nutrient.java
  src/main/java/calocheck/boundedContext/nutrient/repository/NutrientRepository.java
  src/main/java/calocheck/boundedContext/nutrient/service/NutrientService.java
  src/main/resources/templates/usr/cartFoodInfo/addMenu.html
  src/main/resources/templates/usr/cartFoodInfo/list.html
  src/main/resources/templates/usr/cartFoodInfo/total.html
  src/test/java/calocheck/boundedContext/nutrientInfo/service/NutrientInfoServiceTests.java
Labels: enhancement

#75 Enhancement/74
  src/main/java/calocheck/base/initData/NotProd.java
  src/main/java/calocheck/base/util/CriteriaDataExtractor.java
  src/main/java/calocheck/boundedContext/cartFoodInfo/controller/CartFoodInfoController.java
  src/main/java/calocheck/boundedContext/criteria/controller/CriteriaController.java
  src/main/java/calocheck/boundedContext/criteria/entity/Criteria.java
  src/main/java/calocheck/boundedContext/criteria/repository/CriteriaRepository.java
  src/main/java/calocheck/boundedContext/criteria/service/CriteriaService.java
  src/main/java/calocheck/boundedContext/dailyMenu/service/DailyMenuService.java
  src/main/java/calocheck/boundedContext/mealHistory/service/MealHistoryService.java
  src/main/java/calocheck/excel/nutrientCriteria.xlsx
  src/main/resources/templates/usr/criteria/criteria.html
Labels: documentation, enhancement

#77 feat: 글 목록 필터 기능, 검색 기능 강화
  src/main/java/calocheck/boundedContext/post/controller/PostController.java
  src/main/java/calocheck/boundedContext/post/repository/PostRepository.java
  src/main/java/calocheck/boundedContext/post/service/PostService.java
  src/main/resources/templates/usr/post/list.html
Labels: enhancement

#79 bugFix: 멤버, 포스트 순환참조 해결
  src/main/java/calocheck/boundedContext/member/controller/MemberController.java
  src/main/java/calocheck/boundedContext/member/entity/Member.java
  src/main/java/calocheck/boundedContext/post/controller/PostController.java
  src/main/java/calocheck/boundedContext/post/repository/PostRepository.java
  src/main/java/calocheck/boundedContext/post/service/PostService.java
Labels: bug

#82 영양소 권장량, 식단 추가 기능 완료
  src/main/java/calocheck/base/util/CriteriaDataExtractor.java
  src/main/java/calocheck/base/util/FoodDataExtractor.java
  src/main/java/calocheck/boundedContext/cartFoodInfo/controller/CartFoodInfoController.java
  src/main/java/calocheck/boundedContext/criteria/controller/CriteriaController.java
  src/main/java/calocheck/boundedContext/criteria/entity/Criteria.java
  src/main/java/calocheck/boundedContext/criteria/service/CriteriaService.java
  src/main/java/calocheck/boundedContext/mealHistory/service/MealHistoryService.java
  src/main/java/calocheck/boundedContext/member/entity/Member.java
  src/main/java/calocheck/boundedContext/member/service/MemberService.java
  src/main/java/calocheck/excel/nutrientCriteria.xlsx
  src/main/resources/templates/usr/cartFoodInfo/addMenu.html
  src/main/resources/templates/usr/criteria/criteria.html
Labels: enhancement

#94 feat: 커뮤니티 페이지 지연로딩 문제해결, 필터링 기능 눈에 보이게 수정
  build.gradle
  src/main/java/calocheck/boundedContext/post/controller/PostController.java
  src/main/java/calocheck/boundedContext/post/entity/Post.java
  src/main/resources/application.yml
  src/main/resources/templates/usr/post/list.html
  src/main/resources/templates/usr/post/postDetail.html
Labels: enhancement

#93 추천 페이지 리팩토링 및 몇가지 수정
  src/main/java/calocheck/base/initData/NotProd.java
  src/main/java/calocheck/boundedContext/dailyMenu/service/DailyMenuService.java
  src/main/java/calocheck/boundedContext/foodInfo/repository/FoodInfoRepository.java
  src/main/java/calocheck/boundedContext/foodInfo/service/FoodInfoService.java
  src/main/java/calocheck/boundedContext/mealHistory/service/MealHistoryService.java
  src/main/java/calocheck/boundedContext/photo/service/PhotoService.java
  src/main/java/calocheck/boundedContext/recommend/controller/RecommendController.java
  src/main/resources/templates/usr/food/recommendList.html
Labels: bug, enhancement

#97 feat: 음식 검색, 상세 페이지 수정
  build.gradle
  src/main/java/calocheck/base/initData/NotProd.java
  src/main/java/calocheck/base/util/excel/service/ExcelService.java
  src/main/java/calocheck/base/util/s3/service/S3Service.java
  src/main/java/calocheck/boundedContext/cartFoodInfo/controller/CartFoodInfoController.java
  src/main/java/calocheck/boundedContext/cartFoodInfo/dto/CartDTO.java
  src/main/java/calocheck/boundedContext/cartFoodInfo/service/CartFoodInfoService.java
  src/main/java/calocheck/excel/data1.xlsx
  src/main/resources/application.yml
  src/main/resources/templates/usr/cartFoodInfo/list.html
  src/main/resources/templates/usr/foodInfo/details.html
Labels: enhancement

#99 Fix: Google Cloud 관련 기능 주석처리
  src/main/java/calocheck/boundedContext/photo/service/PhotoService.java
  src/main/java/calocheck/boundedContext/post/controller/PostController.java
Labels: bug

#103 feat: 장바구니 수정 사항 구현
  .gitignore
  src/main/generated/calocheck/base/entity/QBaseEntity.java
  src/main/generated/calocheck/boundedContext/cartFoodInfo/entity/QCartFoodInfo.java
  src/main/generated/calocheck/boundedContext/comment/entity/QComment.java
  src/main/generated/calocheck/boundedContext/criteria/entity/QCriteria.java
  src/main/generated/calocheck/boundedContext/dailyMenu/entity/QDailyMenu.java
  src/main/generated/calocheck/boundedContext/foodInfo/entity/QFoodInfo.java
  src/main/generated/calocheck/boundedContext/friend/entity/QFriend.java
  src/main/generated/calocheck/boundedContext/mealHistory/entity/QMealHistory.java
  src/main/generated/calocheck/boundedContext/member/entity/QMember.java
  src/main/generated/calocheck/boundedContext/nutrient/entity/QNutrient.java
  src/main/generated/calocheck/boundedContext/nutrientInfo/entity/QNutrientInfo.java
  src/main/generated/calocheck/boundedContext/post/entity/QPost.java
  src/main/generated/calocheck/boundedContext/postLike/entity/QPostLike.java
  src/main/generated/calocheck/boundedContext/recommend/entity/QRecommend.java
  src/main/generated/calocheck/boundedContext/tracking/entity/QTracking.java
  src/main/java/calocheck/boundedContext/cartFoodInfo/controller/CartFoodInfoController.java
  src/main/java/calocheck/boundedContext/cartFoodInfo/entity/CartFoodInfo.java
  src/main/java/calocheck/boundedContext/cartFoodInfo/service/CartFoodInfoService.java
  src/main/java/calocheck/boundedContext/dailyMenu/entity/DailyMenu.java
  src/main/java/calocheck/boundedContext/dailyMenu/repository/DailyMenuRepository.java
  src/main/java/calocheck/boundedContext/dailyMenu/service/DailyMenuService.java
  src/main/java/calocheck/boundedContext/mealHistory/entity/MealHistory.java
  src/main/java/calocheck/boundedContext/mealHistory/repository/MealHistoryRepository.java
  src/main/java/calocheck/boundedContext/mealHistory/service/MealHistoryService.java
  src/main/java/calocheck/boundedContext/photo/config/S3Config.java
  src/main/resources/templates/usr/cartFoodInfo/addMenu.html
  src/main/resources/templates/usr/cartFoodInfo/list.html
  src/main/resources/templates/usr/cartFoodInfo/total.html
  src/main/resources/templates/usr/foodInfo/details.html
  src/main/resources/templates/usr/foodInfo/search.html
Labels: enhancement

#105 FoodItem 태그 기능
  src/main/java/calocheck/base/initData/NotProd.java
  src/main/java/calocheck/boundedContext/foodInfo/controller/FoodInfoController.java
  src/main/java/calocheck/boundedContext/foodInfo/service/FoodInfoService.java
  src/main/java/calocheck/boundedContext/tag/config/TagConfig.java
  src/main/java/calocheck/boundedContext/tag/entity/Tag.java
  src/main/java/calocheck/boundedContext/tag/repository/TagRepository.java
  src/main/java/calocheck/boundedContext/tag/service/TagService.java
  src/main/resources/templates/usr/food/recommendList.html
  src/main/resources/templates/usr/foodInfo/details.html
Labels: enhancement

#110 식단 캘린더 구현
  src/main/java/calocheck/boundedContext/cartFoodInfo/controller/CartFoodInfoController.java
  src/main/java/calocheck/boundedContext/dailyMenu/dto/DailyMenuDto.java
  src/main/java/calocheck/boundedContext/dailyMenu/entity/DailyMenu.java
  src/main/java/calocheck/boundedContext/foodInfo/entity/FoodInfo.java
  src/main/java/calocheck/boundedContext/mealHistory/controller/MealHistoryController.java
  src/main/java/calocheck/boundedContext/mealHistory/dto/MealHistoryDto.java
  src/main/java/calocheck/boundedContext/mealHistory/service/MealHistoryService.java
  src/main/resources/static/resource/common/mealHistory.css
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/usr/mealHistory/mealHistory.html
Labels: enhancement

#115 GoogeCloud ADC 문제 해결 및 photoService 1차 리팩토링
  .gitignore
  build.gradle
  src/main/java/calocheck/CalocheckApplication.java
  src/main/java/calocheck/base/initData/NotProd.java
  src/main/java/calocheck/boundedContext/home/controller/HomeController.java
  src/main/java/calocheck/boundedContext/photo/config/GCPConfigProperties.java
  src/main/java/calocheck/boundedContext/photo/config/ImageConfig.java
  src/main/java/calocheck/boundedContext/photo/config/S3Config.java
  src/main/java/calocheck/boundedContext/photo/config/S3ConfigProperties.java
  src/main/java/calocheck/boundedContext/photo/service/PhotoService.java
  src/main/java/calocheck/boundedContext/post/controller/PostController.java
  src/main/java/calocheck/boundedContext/tag/config/TagConfig.java
Labels: bug, enhancement

#113 feat: 식품 관련 코드 리팩토링
  src/main/java/calocheck/base/initData/NotProd.java
  src/main/java/calocheck/base/util/FoodDataExtractor.java
  src/main/java/calocheck/base/util/excel/service/ExcelService.java
  src/main/java/calocheck/base/util/s3/service/S3Service.java
  src/main/java/calocheck/boundedContext/cartFoodInfo/controller/CartFoodInfoController.java
  src/main/java/calocheck/boundedContext/cartFoodInfo/service/CartFoodInfoService.java
  src/main/java/calocheck/boundedContext/foodInfo/controller/FoodInfoController.java
  src/main/java/calocheck/boundedContext/foodInfo/entity/FoodInfo.java
  src/main/java/calocheck/boundedContext/foodInfo/repository/FoodInfoRepository.java
  src/main/java/calocheck/boundedContext/foodInfo/service/FoodInfoService.java
  src/main/java/calocheck/boundedContext/mealHistory/entity/MealHistory.java
  src/main/java/calocheck/boundedContext/mealHistory/service/MealHistoryService.java
  src/main/java/calocheck/boundedContext/nutrient/entity/Nutrient.java
  src/main/java/calocheck/boundedContext/nutrient/repository/NutrientRepository.java
  src/main/java/calocheck/boundedContext/nutrient/service/NutrientService.java
  src/main/java/calocheck/boundedContext/nutrientInfo/entity/NutrientInfo.java
  src/main/java/calocheck/boundedContext/nutrientInfo/repository/NutrientInfoRepository.java
  src/main/java/calocheck/boundedContext/nutrientInfo/service/NutrientInfoService.java
  src/main/java/calocheck/boundedContext/recommend/config/RecommendConfig.java
  src/main/resources/static/resource/common/common.css
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/usr/cartFoodInfo/addMenu.html
  src/main/resources/templates/usr/cartFoodInfo/list.html
  src/main/resources/templates/usr/cartFoodInfo/total.html
  src/main/resources/templates/usr/foodInfo/details.html
  src/main/resources/templates/usr/foodInfo/search.html
Labels: enhancement

#120 Fix: tag 중복생성 방지
  src/main/java/calocheck/base/initData/NotProd.java
  src/main/java/calocheck/boundedContext/tag/repository/TagRepository.java
  src/main/java/calocheck/boundedContext/tag/service/TagService.java
Labels: bug

#123 feat: post UI
  src/main/java/calocheck/boundedContext/post/controller/PostController.java
  src/main/java/calocheck/boundedContext/post/entity/Post.java
  src/main/java/calocheck/boundedContext/post/service/PostService.java
  src/main/resources/templates/usr/post/createForm.html
  src/main/resources/templates/usr/post/list.html
  src/main/resources/templates/usr/post/modify.html
  src/main/resources/templates/usr/post/postDetail.html
Labels: enhancement

#125 feat: 장바구니 관련 코드 리팩토링
  src/main/java/calocheck/boundedContext/cartFoodInfo/controller/CartFoodInfoController.java
  src/main/java/calocheck/boundedContext/cartFoodInfo/dto/CartDTO.java
  src/main/java/calocheck/boundedContext/cartFoodInfo/service/CartFoodInfoService.java
  src/main/java/calocheck/boundedContext/criteria/entity/Criteria.java
  src/main/java/calocheck/boundedContext/mealHistory/service/MealHistoryService.java
  src/main/java/calocheck/boundedContext/nutrient/dto/NutrientDTO.java
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/usr/cartFoodInfo/addMenu.html
  src/main/resources/templates/usr/cartFoodInfo/list.html
  src/main/resources/templates/usr/foodInfo/details.html
Labels: bug, enhancement

#126 ImageData 2차 리팩토링 완료
  src/main/java/calocheck/base/initData/NotProd.java
  src/main/java/calocheck/boundedContext/dailyMenu/repository/DailyMenuRepository.java
  src/main/java/calocheck/boundedContext/dailyMenu/service/DailyMenuService.java
  src/main/java/calocheck/boundedContext/foodInfo/controller/FoodInfoController.java
  src/main/java/calocheck/boundedContext/foodInfo/service/FoodInfoService.java
  src/main/java/calocheck/boundedContext/home/controller/HomeController.java
  src/main/java/calocheck/boundedContext/imageData/config/GCPConfigProperties.java
  src/main/java/calocheck/boundedContext/imageData/config/ImageConfig.java
  src/main/java/calocheck/boundedContext/imageData/config/OptimizerConfigProperties.java
  src/main/java/calocheck/boundedContext/imageData/config/S3ConfigProperties.java
  src/main/java/calocheck/boundedContext/imageData/entity/ImageData.java
  src/main/java/calocheck/boundedContext/imageData/imageTarget/ImageTarget.java
  src/main/java/calocheck/boundedContext/imageData/repository/ImageDataRepository.java
  src/main/java/calocheck/boundedContext/imageData/service/ImageDataService.java
  src/main/java/calocheck/boundedContext/photo/service/PhotoService.java
  src/main/java/calocheck/boundedContext/post/controller/PostController.java
  src/main/java/calocheck/boundedContext/post/entity/Post.java
  src/main/java/calocheck/boundedContext/post/service/PostService.java
  src/main/java/calocheck/boundedContext/recommend/controller/RecommendController.java
  src/main/resources/application.yml
  src/main/resources/templates/usr/foodInfo/details.html
  src/main/resources/templates/usr/post/createForm.html
  src/main/resources/templates/usr/post/postDetail.html
Labels: enhancement

#128 추천 기능 리팩토링
  .gitignore
  src/main/java/calocheck/base/initData/NotProd.java
  src/main/java/calocheck/boundedContext/foodInfo/controller/FoodInfoController.java
  src/main/java/calocheck/boundedContext/foodInfo/service/FoodInfoService.java
  src/main/java/calocheck/boundedContext/home/controller/HomeController.java
  src/main/java/calocheck/boundedContext/imageData/service/ImageDataService.java
  src/main/java/calocheck/boundedContext/post/controller/PostController.java
  src/main/java/calocheck/boundedContext/recommend/config/RecommendConfig.java
  src/main/java/calocheck/boundedContext/recommend/config/RecommendConfigProperties.java
  src/main/java/calocheck/boundedContext/recommend/controller/RecommendController.java
  src/main/java/calocheck/boundedContext/recommend/entity/Recommend.java
  src/main/java/calocheck/boundedContext/recommend/service/RecommendService.java
  src/main/resources/application.yml
  src/main/resources/templates/usr/food/recommendList.html
  src/main/resources/templates/usr/recommend/recommendList.html
Labels: enhancement

#132 Tracking 페이지 기능 추가
  src/main/java/calocheck/base/initData/NotProd.java
  src/main/java/calocheck/boundedContext/tracking/controller/TrackingController.java
  src/main/java/calocheck/boundedContext/tracking/entity/Tracking.java
  src/main/java/calocheck/boundedContext/tracking/repository/TrackingRepository.java
  src/main/java/calocheck/boundedContext/tracking/service/TrackingService.java
  src/main/resources/static/resource/common/bodyTracking.css
  src/main/resources/templates/usr/tracking/bodyTracking.html
Labels: enhancement

#130 권장량, 태그 리팩토링
  .gitignore
  src/main/java/calocheck/base/initData/NotProd.java
  src/main/java/calocheck/boundedContext/cartFoodInfo/controller/CartFoodInfoController.java
  src/main/java/calocheck/boundedContext/criteria/config/CriteriaDataExtractor.java
  src/main/java/calocheck/boundedContext/criteria/controller/CriteriaController.java
  src/main/java/calocheck/boundedContext/criteria/entity/Criteria.java
  src/main/java/calocheck/boundedContext/criteria/service/CriteriaService.java
  src/main/java/calocheck/boundedContext/dailyMenu/service/DailyMenuService.java
  src/main/java/calocheck/boundedContext/foodInfo/controller/FoodInfoController.java
  src/main/java/calocheck/boundedContext/foodInfo/service/FoodInfoService.java
  src/main/java/calocheck/boundedContext/mealHistory/controller/MealHistoryController.java
  src/main/java/calocheck/boundedContext/mealHistory/service/MealHistoryService.java
  src/main/java/calocheck/boundedContext/recommend/config/RecommendConfig.java
  src/main/java/calocheck/boundedContext/tag/config/TagConfig.java
  src/main/java/calocheck/boundedContext/tag/config/TagConfigProperties.java
  src/main/java/calocheck/boundedContext/tag/entity/Tag.java
  src/main/java/calocheck/boundedContext/tag/service/TagService.java
  src/main/java/calocheck/excel/nutrientCriteria.xlsx
  src/main/resources/application.yml
  src/main/resources/templates/usr/criteria/criteria.html
Labels: enhancement

#139 Feat: TagServiceTest 작성 완료
  src/test/java/calocheck/boundedContext/foodInfo/service/FoodInfoServiceTests.java
  src/test/java/calocheck/boundedContext/nutrientInfo/service/NutrientInfoServiceTests.java
  src/test/java/calocheck/boundedContext/tag/service/TagServiceTest.java
Labels: enhancement

#142 Feat: ImageDataService 테스트케이스 작성 완료
  src/main/resources/static/img/sample.txt
  src/test/java/calocheck/boundedContext/imageData/service/ImageDataServiceTest.java
  src/test/java/calocheck/boundedContext/tag/service/TagServiceTest.java
Labels: bug, enhancement

#146 CriteriaServiceTest
  src/main/java/calocheck/boundedContext/criteria/config/CriteriaDataExtractor.java
  src/main/java/calocheck/boundedContext/criteria/service/CriteriaService.java
  src/main/java/calocheck/boundedContext/dailyMenu/service/DailyMenuService.java
  src/main/java/calocheck/boundedContext/foodInfo/service/FoodInfoService.java
  src/main/java/calocheck/boundedContext/nutrient/service/NutrientService.java
  src/main/java/calocheck/excel/nutrientCriteria.xlsx
  src/main/resources/application.yml
  src/test/java/calocheck/boundedContext/criteria/service/CriteriaServiceTest.java
Labels: enhancement

#147 feat: post category
  src/main/java/calocheck/base/initData/NotProd.java
  src/main/java/calocheck/boundedContext/notification/entity/Notification.java
  src/main/java/calocheck/boundedContext/post/controller/PostController.java
  src/main/java/calocheck/boundedContext/post/entity/Post.java
  src/main/java/calocheck/boundedContext/post/repository/PostRepository.java
  src/main/java/calocheck/boundedContext/post/service/PostService.java
  src/main/resources/static/resource/common/list.css
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/usr/notification/list.html
  src/main/resources/templates/usr/post/createForm.html
  src/main/resources/templates/usr/post/list.html
  src/main/resources/templates/usr/post/modify.html
  src/main/resources/templates/usr/post/postDetail.html
Labels: enhancement

#154 Fix: Criteria 중복 생성 방지
  src/main/java/calocheck/boundedContext/criteria/config/CriteriaDataExtractor.java
  src/main/java/calocheck/boundedContext/criteria/service/CriteriaService.java
Labels: bug

#162 마이페이지에 권장량, 섭취량 표기
  src/main/java/calocheck/boundedContext/criteria/controller/CriteriaController.java
  src/main/java/calocheck/boundedContext/member/controller/MemberController.java
  src/main/resources/templates/usr/criteria/criteria.html
  src/main/resources/templates/usr/member/mypage.html
Labels: enhancement

#167 feat: 메인 페이지 추가
  src/main/java/calocheck/base/initData/NotProd.java
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/usr/foodInfo/search.html
  src/main/resources/templates/usr/home/main.html
Labels: enhancement

#179 feat: 게시물 수정 시에 사진 삭제 기능
  src/main/java/calocheck/boundedContext/imageData/imageTarget/ImageTarget.java
  src/main/java/calocheck/boundedContext/imageData/service/ImageDataService.java
  src/main/java/calocheck/boundedContext/post/controller/PostController.java
  src/main/resources/templates/usr/post/createForm.html
  src/main/resources/templates/usr/post/list.html
  src/main/resources/templates/usr/post/modify.html
Labels: enhancement

#181 feat: 식품 관련 처리 수정 및 디자인 수정
  src/main/java/calocheck/boundedContext/cartFoodInfo/controller/CartFoodInfoController.java
  src/main/java/calocheck/boundedContext/cartFoodInfo/dto/CartDTO.java
  src/main/java/calocheck/boundedContext/cartFoodInfo/service/CartFoodInfoService.java
  src/main/java/calocheck/boundedContext/dailyMenu/entity/DailyMenu.java
  src/main/java/calocheck/boundedContext/dailyMenu/service/DailyMenuService.java
  src/main/java/calocheck/boundedContext/foodInfo/entity/FoodInfo.java
  src/main/java/calocheck/boundedContext/mealHistory/controller/MealHistoryController.java
  src/main/java/calocheck/boundedContext/mealHistory/repository/MealHistoryRepository.java
  src/main/java/calocheck/boundedContext/mealHistory/service/MealHistoryService.java
  src/main/java/calocheck/boundedContext/member/controller/MemberController.java
  src/main/resources/static/resource/common/mealHistory.css
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/usr/cartFoodInfo/addMenu.html
  src/main/resources/templates/usr/cartFoodInfo/list.html
  src/main/resources/templates/usr/cartFoodInfo/total.html
  src/main/resources/templates/usr/foodInfo/details.html
  src/main/resources/templates/usr/foodInfo/search.html
  src/main/resources/templates/usr/home/main.html
  src/main/resources/templates/usr/mealHistory/mealHistory.html
  src/main/resources/templates/usr/member/friendList.html
  src/main/resources/templates/usr/member/mypage.html
  src/main/resources/templates/usr/post/createForm.html
  src/main/resources/templates/usr/post/list.html
  src/main/resources/templates/usr/post/modify.html
  src/main/resources/templates/usr/post/postDetail.html
  src/main/resources/templates/usr/tracking/bodyTracking.html
  src/test/java/calocheck/boundedContext/cartFoodInfo/controller/CartFoodInfoControllerTests.java
Labels: bug, enhancement

#187 Fix: Recommend Front Update
  src/main/resources/templates/usr/recommend/recommendList.html
Labels: enhancement

#186 feat: Post UI
  src/main/java/calocheck/base/util/Ut.java
  src/main/resources/static/resource/common/list.css
  src/main/resources/templates/usr/post/list.html
  src/main/resources/templates/usr/post/postDetail.html
Labels: enhancement

#191 Feat: add Logo Image
  src/main/resources/templates/common/fragments/header.html
Labels: documentation

#193 Fix : 아이콘 및 위치 수정
  src/main/resources/templates/common/fragments/header.html
Labels: enhancement

#195 Docs: readMe 파일 작성
  README.md
Labels: documentation
